name: MinnaEP1
options:
  bundleIdPrefix: ai.minna
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    PRODUCT_NAME: "Minna EP-1"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
  configs:
    Debug:
      # Sign to run locally (no team required)
      CODE_SIGN_IDENTITY: "-"
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGNING_ALLOWED: NO
      ENABLE_HARDENED_RUNTIME: NO
    Release:
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      ENABLE_HARDENED_RUNTIME: YES

targets:
  MinnaEP1:
    type: application
    platform: macOS
    sources:
      - path: .
        excludes:
          - "**/*.xcodeproj"
          - "**/*.xcworkspace"
          - project.yml
          - README.md
    info:
      path: Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.minna.ep1
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Info.plist
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGNING_REQUIRED: NO
          CODE_SIGNING_ALLOWED: NO
          CODE_SIGN_ENTITLEMENTS: ""
        Release:
          CODE_SIGN_ENTITLEMENTS: MinnaEP1.entitlements
    preBuildScripts: []
    postBuildScripts: []

schemes:
  MinnaEP1:
    build:
      targets:
        MinnaEP1: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
